/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DeploymentRollback stores the information required to rollback a deployment.
 */
public class Extensionsv1beta1DeploymentRollback {
    /**
     * APIVersion defines the versioned schema of this representation of an
     * object. Servers should convert recognized schemas to the latest internal
     * value, and may reject unrecognized values. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources.
     */
    @JsonProperty(value = "apiVersion")
    private String apiVersion;

    /**
     * Kind is a string value representing the REST resource this object
     * represents. Servers may infer this from the endpoint the client submits
     * requests to. Cannot be updated. In CamelCase. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds.
     */
    @JsonProperty(value = "kind")
    private String kind;

    /**
     * Required: This must match the Name of a deployment.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The config of this deployment rollback.
     */
    @JsonProperty(value = "rollbackTo", required = true)
    private Extensionsv1beta1RollbackConfig rollbackTo;

    /**
     * The annotations to be updated to a deployment.
     */
    @JsonProperty(value = "updatedAnnotations")
    private Map<String, String> updatedAnnotations;

    /**
     * Get the apiVersion value.
     *
     * @return the apiVersion value
     */
    public String apiVersion() {
        return this.apiVersion;
    }

    /**
     * Set the apiVersion value.
     *
     * @param apiVersion the apiVersion value to set
     * @return the Extensionsv1beta1DeploymentRollback object itself.
     */
    public Extensionsv1beta1DeploymentRollback withApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Get the kind value.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set the kind value.
     *
     * @param kind the kind value to set
     * @return the Extensionsv1beta1DeploymentRollback object itself.
     */
    public Extensionsv1beta1DeploymentRollback withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Extensionsv1beta1DeploymentRollback object itself.
     */
    public Extensionsv1beta1DeploymentRollback withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the rollbackTo value.
     *
     * @return the rollbackTo value
     */
    public Extensionsv1beta1RollbackConfig rollbackTo() {
        return this.rollbackTo;
    }

    /**
     * Set the rollbackTo value.
     *
     * @param rollbackTo the rollbackTo value to set
     * @return the Extensionsv1beta1DeploymentRollback object itself.
     */
    public Extensionsv1beta1DeploymentRollback withRollbackTo(Extensionsv1beta1RollbackConfig rollbackTo) {
        this.rollbackTo = rollbackTo;
        return this;
    }

    /**
     * Get the updatedAnnotations value.
     *
     * @return the updatedAnnotations value
     */
    public Map<String, String> updatedAnnotations() {
        return this.updatedAnnotations;
    }

    /**
     * Set the updatedAnnotations value.
     *
     * @param updatedAnnotations the updatedAnnotations value to set
     * @return the Extensionsv1beta1DeploymentRollback object itself.
     */
    public Extensionsv1beta1DeploymentRollback withUpdatedAnnotations(Map<String, String> updatedAnnotations) {
        this.updatedAnnotations = updatedAnnotations;
        return this;
    }

}
