/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * describes the attributes of a scale subresource.
 */
public class Extensionsv1beta1ScaleSpec {
    /**
     * desired number of instances for the scaled object.
     */
    @JsonProperty(value = "replicas")
    private Integer replicas;

    /**
     * Get the replicas value.
     *
     * @return the replicas value
     */
    public Integer replicas() {
        return this.replicas;
    }

    /**
     * Set the replicas value.
     *
     * @param replicas the replicas value to set
     * @return the Extensionsv1beta1ScaleSpec object itself.
     */
    public Extensionsv1beta1ScaleSpec withReplicas(Integer replicas) {
        this.replicas = replicas;
        return this;
    }

}
