/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Affinity is a group of affinity scheduling rules.
 */
public class V1Affinity {
    /**
     * Describes node affinity scheduling rules for the pod.
     */
    @JsonProperty(value = "nodeAffinity")
    private V1NodeAffinity nodeAffinity;

    /**
     * Describes pod affinity scheduling rules (e.g. co-locate this pod in the
     * same node, zone, etc. as some other pod(s)).
     */
    @JsonProperty(value = "podAffinity")
    private V1PodAffinity podAffinity;

    /**
     * Describes pod anti-affinity scheduling rules (e.g. avoid putting this
     * pod in the same node, zone, etc. as some other pod(s)).
     */
    @JsonProperty(value = "podAntiAffinity")
    private V1PodAntiAffinity podAntiAffinity;

    /**
     * Get the nodeAffinity value.
     *
     * @return the nodeAffinity value
     */
    public V1NodeAffinity nodeAffinity() {
        return this.nodeAffinity;
    }

    /**
     * Set the nodeAffinity value.
     *
     * @param nodeAffinity the nodeAffinity value to set
     * @return the V1Affinity object itself.
     */
    public V1Affinity withNodeAffinity(V1NodeAffinity nodeAffinity) {
        this.nodeAffinity = nodeAffinity;
        return this;
    }

    /**
     * Get the podAffinity value.
     *
     * @return the podAffinity value
     */
    public V1PodAffinity podAffinity() {
        return this.podAffinity;
    }

    /**
     * Set the podAffinity value.
     *
     * @param podAffinity the podAffinity value to set
     * @return the V1Affinity object itself.
     */
    public V1Affinity withPodAffinity(V1PodAffinity podAffinity) {
        this.podAffinity = podAffinity;
        return this;
    }

    /**
     * Get the podAntiAffinity value.
     *
     * @return the podAntiAffinity value
     */
    public V1PodAntiAffinity podAntiAffinity() {
        return this.podAntiAffinity;
    }

    /**
     * Set the podAntiAffinity value.
     *
     * @param podAntiAffinity the podAntiAffinity value to set
     * @return the V1Affinity object itself.
     */
    public V1Affinity withPodAntiAffinity(V1PodAntiAffinity podAntiAffinity) {
        this.podAntiAffinity = podAntiAffinity;
        return this;
    }

}
