/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PodPresetSpec is a description of a pod injection policy.
 */
public class V1alpha1PodPresetSpec {
    /**
     * Env defines the collection of EnvVar to inject into containers.
     */
    @JsonProperty(value = "env")
    private List<V1EnvVar> env;

    /**
     * EnvFrom defines the collection of EnvFromSource to inject into
     * containers.
     */
    @JsonProperty(value = "envFrom")
    private List<V1EnvFromSource> envFrom;

    /**
     * Selector is a label query over a set of resources, in this case pods.
     * Required.
     */
    @JsonProperty(value = "selector")
    private V1LabelSelector selector;

    /**
     * VolumeMounts defines the collection of VolumeMount to inject into
     * containers.
     */
    @JsonProperty(value = "volumeMounts")
    private List<V1VolumeMount> volumeMounts;

    /**
     * Volumes defines the collection of Volume to inject into the pod.
     */
    @JsonProperty(value = "volumes")
    private List<V1Volume> volumes;

    /**
     * Get the env value.
     *
     * @return the env value
     */
    public List<V1EnvVar> env() {
        return this.env;
    }

    /**
     * Set the env value.
     *
     * @param env the env value to set
     * @return the V1alpha1PodPresetSpec object itself.
     */
    public V1alpha1PodPresetSpec withEnv(List<V1EnvVar> env) {
        this.env = env;
        return this;
    }

    /**
     * Get the envFrom value.
     *
     * @return the envFrom value
     */
    public List<V1EnvFromSource> envFrom() {
        return this.envFrom;
    }

    /**
     * Set the envFrom value.
     *
     * @param envFrom the envFrom value to set
     * @return the V1alpha1PodPresetSpec object itself.
     */
    public V1alpha1PodPresetSpec withEnvFrom(List<V1EnvFromSource> envFrom) {
        this.envFrom = envFrom;
        return this;
    }

    /**
     * Get the selector value.
     *
     * @return the selector value
     */
    public V1LabelSelector selector() {
        return this.selector;
    }

    /**
     * Set the selector value.
     *
     * @param selector the selector value to set
     * @return the V1alpha1PodPresetSpec object itself.
     */
    public V1alpha1PodPresetSpec withSelector(V1LabelSelector selector) {
        this.selector = selector;
        return this;
    }

    /**
     * Get the volumeMounts value.
     *
     * @return the volumeMounts value
     */
    public List<V1VolumeMount> volumeMounts() {
        return this.volumeMounts;
    }

    /**
     * Set the volumeMounts value.
     *
     * @param volumeMounts the volumeMounts value to set
     * @return the V1alpha1PodPresetSpec object itself.
     */
    public V1alpha1PodPresetSpec withVolumeMounts(List<V1VolumeMount> volumeMounts) {
        this.volumeMounts = volumeMounts;
        return this;
    }

    /**
     * Get the volumes value.
     *
     * @return the volumes value
     */
    public List<V1Volume> volumes() {
        return this.volumes;
    }

    /**
     * Set the volumes value.
     *
     * @param volumes the volumes value to set
     * @return the V1alpha1PodPresetSpec object itself.
     */
    public V1alpha1PodPresetSpec withVolumes(List<V1Volume> volumes) {
        this.volumes = volumes;
        return this;
    }

}
