/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RoleRef contains information that points to the role being used.
 */
public class V1alpha1RoleRef {
    /**
     * APIGroup is the group for the resource being referenced.
     */
    @JsonProperty(value = "apiGroup", required = true)
    private String apiGroup;

    /**
     * Kind is the type of resource being referenced.
     */
    @JsonProperty(value = "kind", required = true)
    private String kind;

    /**
     * Name is the name of resource being referenced.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * Get the apiGroup value.
     *
     * @return the apiGroup value
     */
    public String apiGroup() {
        return this.apiGroup;
    }

    /**
     * Set the apiGroup value.
     *
     * @param apiGroup the apiGroup value to set
     * @return the V1alpha1RoleRef object itself.
     */
    public V1alpha1RoleRef withApiGroup(String apiGroup) {
        this.apiGroup = apiGroup;
        return this;
    }

    /**
     * Get the kind value.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set the kind value.
     *
     * @param kind the kind value to set
     * @return the V1alpha1RoleRef object itself.
     */
    public V1alpha1RoleRef withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V1alpha1RoleRef object itself.
     */
    public V1alpha1RoleRef withName(String name) {
        this.name = name;
        return this;
    }

}
