/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * APIResource specifies the name of a resource and whether it is namespaced.
 */
public class V1APIResource {
    /**
     * kind is the kind for the resource (e.g. 'Foo' is the kind for a resource
     * 'foo').
     */
    @JsonProperty(value = "kind", required = true)
    private String kind;

    /**
     * name is the name of the resource.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * namespaced indicates if a resource is namespaced or not.
     */
    @JsonProperty(value = "namespaced", required = true)
    private boolean namespaced;

    /**
     * shortNames is a list of suggested short names of the resource.
     */
    @JsonProperty(value = "shortNames")
    private List<String> shortNames;

    /**
     * verbs is a list of supported kube verbs (this includes get, list, watch,
     * create, update, patch, delete, deletecollection, and proxy).
     */
    @JsonProperty(value = "verbs", required = true)
    private List<String> verbs;

    /**
     * Get the kind value.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set the kind value.
     *
     * @param kind the kind value to set
     * @return the V1APIResource object itself.
     */
    public V1APIResource withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V1APIResource object itself.
     */
    public V1APIResource withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the namespaced value.
     *
     * @return the namespaced value
     */
    public boolean namespaced() {
        return this.namespaced;
    }

    /**
     * Set the namespaced value.
     *
     * @param namespaced the namespaced value to set
     * @return the V1APIResource object itself.
     */
    public V1APIResource withNamespaced(boolean namespaced) {
        this.namespaced = namespaced;
        return this;
    }

    /**
     * Get the shortNames value.
     *
     * @return the shortNames value
     */
    public List<String> shortNames() {
        return this.shortNames;
    }

    /**
     * Set the shortNames value.
     *
     * @param shortNames the shortNames value to set
     * @return the V1APIResource object itself.
     */
    public V1APIResource withShortNames(List<String> shortNames) {
        this.shortNames = shortNames;
        return this;
    }

    /**
     * Get the verbs value.
     *
     * @return the verbs value
     */
    public List<String> verbs() {
        return this.verbs;
    }

    /**
     * Set the verbs value.
     *
     * @param verbs the verbs value to set
     * @return the V1APIResource object itself.
     */
    public V1APIResource withVerbs(List<String> verbs) {
        this.verbs = verbs;
        return this;
    }

}
