/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AttachedVolume describes a volume attached to a node.
 */
public class V1AttachedVolume {
    /**
     * DevicePath represents the device path where the volume should be
     * available.
     */
    @JsonProperty(value = "devicePath", required = true)
    private String devicePath;

    /**
     * Name of the attached volume.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * Get the devicePath value.
     *
     * @return the devicePath value
     */
    public String devicePath() {
        return this.devicePath;
    }

    /**
     * Set the devicePath value.
     *
     * @param devicePath the devicePath value to set
     * @return the V1AttachedVolume object itself.
     */
    public V1AttachedVolume withDevicePath(String devicePath) {
        this.devicePath = devicePath;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V1AttachedVolume object itself.
     */
    public V1AttachedVolume withName(String name) {
        this.name = name;
        return this;
    }

}
