/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The V1beta1CertificateSigningRequestStatus model.
 */
public class V1beta1CertificateSigningRequestStatus {
    /**
     * If request was approved, the controller will place the issued
     * certificate here.
     */
    @JsonProperty(value = "certificate")
    private byte[] certificate;

    /**
     * Conditions applied to the request, such as approval or denial.
     */
    @JsonProperty(value = "conditions")
    private List<V1beta1CertificateSigningRequestCondition> conditions;

    /**
     * Get the certificate value.
     *
     * @return the certificate value
     */
    public byte[] certificate() {
        return this.certificate;
    }

    /**
     * Set the certificate value.
     *
     * @param certificate the certificate value to set
     * @return the V1beta1CertificateSigningRequestStatus object itself.
     */
    public V1beta1CertificateSigningRequestStatus withCertificate(byte[] certificate) {
        this.certificate = certificate;
        return this;
    }

    /**
     * Get the conditions value.
     *
     * @return the conditions value
     */
    public List<V1beta1CertificateSigningRequestCondition> conditions() {
        return this.conditions;
    }

    /**
     * Set the conditions value.
     *
     * @param conditions the conditions value to set
     * @return the V1beta1CertificateSigningRequestStatus object itself.
     */
    public V1beta1CertificateSigningRequestStatus withConditions(List<V1beta1CertificateSigningRequestCondition> conditions) {
        this.conditions = conditions;
        return this;
    }

}
