/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * HTTPIngressRuleValue is a list of http selectors pointing to backends. In
 * the example: http://&lt;host&gt;/&lt;path&gt;?&lt;searchpart&gt; -&gt;
 * backend where where parts of the url correspond to RFC 3986, this resource
 * will be used to match against everything after the last '/' and before the
 * first '?' or '#'.
 */
public class V1beta1HTTPIngressRuleValue {
    /**
     * A collection of paths that map requests to backends.
     */
    @JsonProperty(value = "paths", required = true)
    private List<V1beta1HTTPIngressPath> paths;

    /**
     * Get the paths value.
     *
     * @return the paths value
     */
    public List<V1beta1HTTPIngressPath> paths() {
        return this.paths;
    }

    /**
     * Set the paths value.
     *
     * @param paths the paths value to set
     * @return the V1beta1HTTPIngressRuleValue object itself.
     */
    public V1beta1HTTPIngressRuleValue withPaths(List<V1beta1HTTPIngressPath> paths) {
        this.paths = paths;
        return this;
    }

}
