/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * IngressBackend describes all endpoints for a given service and port.
 */
public class V1beta1IngressBackend {
    /**
     * Specifies the name of the referenced service.
     */
    @JsonProperty(value = "serviceName", required = true)
    private String serviceName;

    /**
     * Specifies the port of the referenced service.
     */
    @JsonProperty(value = "servicePort", required = true)
    private String servicePort;

    /**
     * Get the serviceName value.
     *
     * @return the serviceName value
     */
    public String serviceName() {
        return this.serviceName;
    }

    /**
     * Set the serviceName value.
     *
     * @param serviceName the serviceName value to set
     * @return the V1beta1IngressBackend object itself.
     */
    public V1beta1IngressBackend withServiceName(String serviceName) {
        this.serviceName = serviceName;
        return this;
    }

    /**
     * Get the servicePort value.
     *
     * @return the servicePort value
     */
    public String servicePort() {
        return this.servicePort;
    }

    /**
     * Set the servicePort value.
     *
     * @param servicePort the servicePort value to set
     * @return the V1beta1IngressBackend object itself.
     */
    public V1beta1IngressBackend withServicePort(String servicePort) {
        this.servicePort = servicePort;
        return this;
    }

}
