/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * IngressTLS describes the transport layer security associated with an
 * Ingress.
 */
public class V1beta1IngressTLS {
    /**
     * Hosts are a list of hosts included in the TLS certificate. The values in
     * this list must match the name/s used in the tlsSecret. Defaults to the
     * wildcard host setting for the loadbalancer controller fulfilling this
     * Ingress, if left unspecified.
     */
    @JsonProperty(value = "hosts")
    private List<String> hosts;

    /**
     * SecretName is the name of the secret used to terminate SSL traffic on
     * 443. Field is left optional to allow SSL routing based on SNI hostname
     * alone. If the SNI host in a listener conflicts with the "Host" header
     * field used by an IngressRule, the SNI host is used for termination and
     * value of the Host header is used for routing.
     */
    @JsonProperty(value = "secretName")
    private String secretName;

    /**
     * Get the hosts value.
     *
     * @return the hosts value
     */
    public List<String> hosts() {
        return this.hosts;
    }

    /**
     * Set the hosts value.
     *
     * @param hosts the hosts value to set
     * @return the V1beta1IngressTLS object itself.
     */
    public V1beta1IngressTLS withHosts(List<String> hosts) {
        this.hosts = hosts;
        return this;
    }

    /**
     * Get the secretName value.
     *
     * @return the secretName value
     */
    public String secretName() {
        return this.secretName;
    }

    /**
     * Set the secretName value.
     *
     * @param secretName the secretName value to set
     * @return the V1beta1IngressTLS object itself.
     */
    public V1beta1IngressTLS withSecretName(String secretName) {
        this.secretName = secretName;
        return this;
    }

}
