/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ReplicaSet represents the configuration of a ReplicaSet.
 */
public class V1beta1ReplicaSet {
    /**
     * APIVersion defines the versioned schema of this representation of an
     * object. Servers should convert recognized schemas to the latest internal
     * value, and may reject unrecognized values. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources.
     */
    @JsonProperty(value = "apiVersion")
    private String apiVersion;

    /**
     * Kind is a string value representing the REST resource this object
     * represents. Servers may infer this from the endpoint the client submits
     * requests to. Cannot be updated. In CamelCase. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds.
     */
    @JsonProperty(value = "kind")
    private String kind;

    /**
     * If the Labels of a ReplicaSet are empty, they are defaulted to be the
     * same as the Pod(s) that the ReplicaSet manages. Standard object's
     * metadata. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata.
     */
    @JsonProperty(value = "metadata")
    private V1ObjectMeta metadata;

    /**
     * Spec defines the specification of the desired behavior of the
     * ReplicaSet. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#spec-and-status.
     */
    @JsonProperty(value = "spec")
    private V1beta1ReplicaSetSpec spec;

    /**
     * Status is the most recently observed status of the ReplicaSet. This data
     * may be out of date by some window of time. Populated by the system.
     * Read-only. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#spec-and-status.
     */
    @JsonProperty(value = "status")
    private V1beta1ReplicaSetStatus status;

    /**
     * Get the apiVersion value.
     *
     * @return the apiVersion value
     */
    public String apiVersion() {
        return this.apiVersion;
    }

    /**
     * Set the apiVersion value.
     *
     * @param apiVersion the apiVersion value to set
     * @return the V1beta1ReplicaSet object itself.
     */
    public V1beta1ReplicaSet withApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Get the kind value.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set the kind value.
     *
     * @param kind the kind value to set
     * @return the V1beta1ReplicaSet object itself.
     */
    public V1beta1ReplicaSet withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the metadata value.
     *
     * @return the metadata value
     */
    public V1ObjectMeta metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata value.
     *
     * @param metadata the metadata value to set
     * @return the V1beta1ReplicaSet object itself.
     */
    public V1beta1ReplicaSet withMetadata(V1ObjectMeta metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get the spec value.
     *
     * @return the spec value
     */
    public V1beta1ReplicaSetSpec spec() {
        return this.spec;
    }

    /**
     * Set the spec value.
     *
     * @param spec the spec value to set
     * @return the V1beta1ReplicaSet object itself.
     */
    public V1beta1ReplicaSet withSpec(V1beta1ReplicaSetSpec spec) {
        this.spec = spec;
        return this;
    }

    /**
     * Get the status value.
     *
     * @return the status value
     */
    public V1beta1ReplicaSetStatus status() {
        return this.status;
    }

    /**
     * Set the status value.
     *
     * @param status the status value to set
     * @return the V1beta1ReplicaSet object itself.
     */
    public V1beta1ReplicaSet withStatus(V1beta1ReplicaSetStatus status) {
        this.status = status;
        return this;
    }

}
