/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The V1beta1NetworkPolicyPort model.
 */
public class V1beta1NetworkPolicyPort {
    /**
     * If specified, the port on the given protocol.  This can either be a
     * numerical or named port on a pod.  If this field is not provided, this
     * matches all port names and numbers. If present, only traffic on the
     * specified protocol AND port will be matched.
     */
    @JsonProperty(value = "port")
    private String port;

    /**
     * Optional.  The protocol (TCP or UDP) which traffic must match. If not
     * specified, this field defaults to TCP.
     */
    @JsonProperty(value = "protocol")
    private String protocol;

    /**
     * Get the port value.
     *
     * @return the port value
     */
    public String port() {
        return this.port;
    }

    /**
     * Set the port value.
     *
     * @param port the port value to set
     * @return the V1beta1NetworkPolicyPort object itself.
     */
    public V1beta1NetworkPolicyPort withPort(String port) {
        this.port = port;
        return this;
    }

    /**
     * Get the protocol value.
     *
     * @return the protocol value
     */
    public String protocol() {
        return this.protocol;
    }

    /**
     * Set the protocol value.
     *
     * @param protocol the protocol value to set
     * @return the V1beta1NetworkPolicyPort object itself.
     */
    public V1beta1NetworkPolicyPort withProtocol(String protocol) {
        this.protocol = protocol;
        return this;
    }

}
