/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DaemonSetStatus represents the current status of a daemon set.
 */
public class V1beta1DaemonSetStatus {
    /**
     * The number of nodes that are running at least 1 daemon pod and are
     * supposed to run the daemon pod. More info:
     * http://releases.k8s.io/HEAD/docs/admin/daemons.md.
     */
    @JsonProperty(value = "currentNumberScheduled", required = true)
    private int currentNumberScheduled;

    /**
     * The total number of nodes that should be running the daemon pod
     * (including nodes correctly running the daemon pod). More info:
     * http://releases.k8s.io/HEAD/docs/admin/daemons.md.
     */
    @JsonProperty(value = "desiredNumberScheduled", required = true)
    private int desiredNumberScheduled;

    /**
     * The number of nodes that should be running the daemon pod and have one
     * or more of the daemon pod running and available (ready for at least
     * spec.minReadySeconds).
     */
    @JsonProperty(value = "numberAvailable")
    private Integer numberAvailable;

    /**
     * The number of nodes that are running the daemon pod, but are not
     * supposed to run the daemon pod. More info:
     * http://releases.k8s.io/HEAD/docs/admin/daemons.md.
     */
    @JsonProperty(value = "numberMisscheduled", required = true)
    private int numberMisscheduled;

    /**
     * The number of nodes that should be running the daemon pod and have one
     * or more of the daemon pod running and ready.
     */
    @JsonProperty(value = "numberReady", required = true)
    private int numberReady;

    /**
     * The number of nodes that should be running the daemon pod and have none
     * of the daemon pod running and available (ready for at least
     * spec.minReadySeconds).
     */
    @JsonProperty(value = "numberUnavailable")
    private Integer numberUnavailable;

    /**
     * The most recent generation observed by the daemon set controller.
     */
    @JsonProperty(value = "observedGeneration")
    private Long observedGeneration;

    /**
     * The total number of nodes that are running updated daemon pod.
     */
    @JsonProperty(value = "updatedNumberScheduled")
    private Integer updatedNumberScheduled;

    /**
     * Get the currentNumberScheduled value.
     *
     * @return the currentNumberScheduled value
     */
    public int currentNumberScheduled() {
        return this.currentNumberScheduled;
    }

    /**
     * Set the currentNumberScheduled value.
     *
     * @param currentNumberScheduled the currentNumberScheduled value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withCurrentNumberScheduled(int currentNumberScheduled) {
        this.currentNumberScheduled = currentNumberScheduled;
        return this;
    }

    /**
     * Get the desiredNumberScheduled value.
     *
     * @return the desiredNumberScheduled value
     */
    public int desiredNumberScheduled() {
        return this.desiredNumberScheduled;
    }

    /**
     * Set the desiredNumberScheduled value.
     *
     * @param desiredNumberScheduled the desiredNumberScheduled value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withDesiredNumberScheduled(int desiredNumberScheduled) {
        this.desiredNumberScheduled = desiredNumberScheduled;
        return this;
    }

    /**
     * Get the numberAvailable value.
     *
     * @return the numberAvailable value
     */
    public Integer numberAvailable() {
        return this.numberAvailable;
    }

    /**
     * Set the numberAvailable value.
     *
     * @param numberAvailable the numberAvailable value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withNumberAvailable(Integer numberAvailable) {
        this.numberAvailable = numberAvailable;
        return this;
    }

    /**
     * Get the numberMisscheduled value.
     *
     * @return the numberMisscheduled value
     */
    public int numberMisscheduled() {
        return this.numberMisscheduled;
    }

    /**
     * Set the numberMisscheduled value.
     *
     * @param numberMisscheduled the numberMisscheduled value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withNumberMisscheduled(int numberMisscheduled) {
        this.numberMisscheduled = numberMisscheduled;
        return this;
    }

    /**
     * Get the numberReady value.
     *
     * @return the numberReady value
     */
    public int numberReady() {
        return this.numberReady;
    }

    /**
     * Set the numberReady value.
     *
     * @param numberReady the numberReady value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withNumberReady(int numberReady) {
        this.numberReady = numberReady;
        return this;
    }

    /**
     * Get the numberUnavailable value.
     *
     * @return the numberUnavailable value
     */
    public Integer numberUnavailable() {
        return this.numberUnavailable;
    }

    /**
     * Set the numberUnavailable value.
     *
     * @param numberUnavailable the numberUnavailable value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withNumberUnavailable(Integer numberUnavailable) {
        this.numberUnavailable = numberUnavailable;
        return this;
    }

    /**
     * Get the observedGeneration value.
     *
     * @return the observedGeneration value
     */
    public Long observedGeneration() {
        return this.observedGeneration;
    }

    /**
     * Set the observedGeneration value.
     *
     * @param observedGeneration the observedGeneration value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withObservedGeneration(Long observedGeneration) {
        this.observedGeneration = observedGeneration;
        return this;
    }

    /**
     * Get the updatedNumberScheduled value.
     *
     * @return the updatedNumberScheduled value
     */
    public Integer updatedNumberScheduled() {
        return this.updatedNumberScheduled;
    }

    /**
     * Set the updatedNumberScheduled value.
     *
     * @param updatedNumberScheduled the updatedNumberScheduled value to set
     * @return the V1beta1DaemonSetStatus object itself.
     */
    public V1beta1DaemonSetStatus withUpdatedNumberScheduled(Integer updatedNumberScheduled) {
        this.updatedNumberScheduled = updatedNumberScheduled;
        return this;
    }

}
