/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PodDisruptionBudgetSpec is a description of a PodDisruptionBudget.
 */
public class V1beta1PodDisruptionBudgetSpec {
    /**
     * An eviction is allowed if at least "minAvailable" pods selected by
     * "selector" will still be available after the eviction, i.e. even in the
     * absence of the evicted pod.  So for example you can prevent all
     * voluntary evictions by specifying "100%".
     */
    @JsonProperty(value = "minAvailable")
    private String minAvailable;

    /**
     * Label query over pods whose evictions are managed by the disruption
     * budget.
     */
    @JsonProperty(value = "selector")
    private V1LabelSelector selector;

    /**
     * Get the minAvailable value.
     *
     * @return the minAvailable value
     */
    public String minAvailable() {
        return this.minAvailable;
    }

    /**
     * Set the minAvailable value.
     *
     * @param minAvailable the minAvailable value to set
     * @return the V1beta1PodDisruptionBudgetSpec object itself.
     */
    public V1beta1PodDisruptionBudgetSpec withMinAvailable(String minAvailable) {
        this.minAvailable = minAvailable;
        return this;
    }

    /**
     * Get the selector value.
     *
     * @return the selector value
     */
    public V1LabelSelector selector() {
        return this.selector;
    }

    /**
     * Set the selector value.
     *
     * @param selector the selector value to set
     * @return the V1beta1PodDisruptionBudgetSpec object itself.
     */
    public V1beta1PodDisruptionBudgetSpec withSelector(V1LabelSelector selector) {
        this.selector = selector;
        return this;
    }

}
