/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This NetworkPolicyIngressRule matches traffic if and only if the traffic
 * matches both ports AND from.
 */
public class V1beta1NetworkPolicyIngressRule {
    /**
     * List of sources which should be able to access the pods selected for
     * this rule. Items in this list are combined using a logical OR operation.
     * If this field is not provided, this rule matches all sources (traffic
     * not restricted by source). If this field is empty, this rule matches no
     * sources (no traffic matches). If this field is present and contains at
     * least on item, this rule allows traffic only if the traffic matches at
     * least one item in the from list.
     */
    @JsonProperty(value = "from")
    private List<V1beta1NetworkPolicyPeer> from;

    /**
     * List of ports which should be made accessible on the pods selected for
     * this rule. Each item in this list is combined using a logical OR. If
     * this field is not provided, this rule matches all ports (traffic not
     * restricted by port). If this field is empty, this rule matches no ports
     * (no traffic matches). If this field is present and contains at least one
     * item, then this rule allows traffic only if the traffic matches at least
     * one port in the list.
     */
    @JsonProperty(value = "ports")
    private List<V1beta1NetworkPolicyPort> ports;

    /**
     * Get the from value.
     *
     * @return the from value
     */
    public List<V1beta1NetworkPolicyPeer> from() {
        return this.from;
    }

    /**
     * Set the from value.
     *
     * @param from the from value to set
     * @return the V1beta1NetworkPolicyIngressRule object itself.
     */
    public V1beta1NetworkPolicyIngressRule withFrom(List<V1beta1NetworkPolicyPeer> from) {
        this.from = from;
        return this;
    }

    /**
     * Get the ports value.
     *
     * @return the ports value
     */
    public List<V1beta1NetworkPolicyPort> ports() {
        return this.ports;
    }

    /**
     * Set the ports value.
     *
     * @param ports the ports value to set
     * @return the V1beta1NetworkPolicyIngressRule object itself.
     */
    public V1beta1NetworkPolicyIngressRule withPorts(List<V1beta1NetworkPolicyPort> ports) {
        this.ports = ports;
        return this;
    }

}
