/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Describe a container image.
 */
public class V1ContainerImage {
    /**
     * Names by which this image is known. e.g.
     * ["gcr.io/google_containers/hyperkube:v1.0.7",
     * "dockerhub.io/google_containers/hyperkube:v1.0.7"].
     */
    @JsonProperty(value = "names", required = true)
    private List<String> names;

    /**
     * The size of the image in bytes.
     */
    @JsonProperty(value = "sizeBytes")
    private Long sizeBytes;

    /**
     * Get the names value.
     *
     * @return the names value
     */
    public List<String> names() {
        return this.names;
    }

    /**
     * Set the names value.
     *
     * @param names the names value to set
     * @return the V1ContainerImage object itself.
     */
    public V1ContainerImage withNames(List<String> names) {
        this.names = names;
        return this;
    }

    /**
     * Get the sizeBytes value.
     *
     * @return the sizeBytes value
     */
    public Long sizeBytes() {
        return this.sizeBytes;
    }

    /**
     * Set the sizeBytes value.
     *
     * @param sizeBytes the sizeBytes value to set
     * @return the V1ContainerImage object itself.
     */
    public V1ContainerImage withSizeBytes(Long sizeBytes) {
        this.sizeBytes = sizeBytes;
        return this;
    }

}
