/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ContainerStateTerminated is a terminated state of a container.
 */
public class V1ContainerStateTerminated {
    /**
     * Container's ID in the format 'docker://&lt;container_id&gt;'.
     */
    @JsonProperty(value = "containerID")
    private String containerID;

    /**
     * Exit status from the last termination of the container.
     */
    @JsonProperty(value = "exitCode", required = true)
    private int exitCode;

    /**
     * Time at which the container last terminated.
     */
    @JsonProperty(value = "finishedAt")
    private DateTime finishedAt;

    /**
     * Message regarding the last termination of the container.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * (brief) reason from the last termination of the container.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /**
     * Signal from the last termination of the container.
     */
    @JsonProperty(value = "signal")
    private Integer signal;

    /**
     * Time at which previous execution of the container started.
     */
    @JsonProperty(value = "startedAt")
    private DateTime startedAt;

    /**
     * Get the containerID value.
     *
     * @return the containerID value
     */
    public String containerID() {
        return this.containerID;
    }

    /**
     * Set the containerID value.
     *
     * @param containerID the containerID value to set
     * @return the V1ContainerStateTerminated object itself.
     */
    public V1ContainerStateTerminated withContainerID(String containerID) {
        this.containerID = containerID;
        return this;
    }

    /**
     * Get the exitCode value.
     *
     * @return the exitCode value
     */
    public int exitCode() {
        return this.exitCode;
    }

    /**
     * Set the exitCode value.
     *
     * @param exitCode the exitCode value to set
     * @return the V1ContainerStateTerminated object itself.
     */
    public V1ContainerStateTerminated withExitCode(int exitCode) {
        this.exitCode = exitCode;
        return this;
    }

    /**
     * Get the finishedAt value.
     *
     * @return the finishedAt value
     */
    public DateTime finishedAt() {
        return this.finishedAt;
    }

    /**
     * Set the finishedAt value.
     *
     * @param finishedAt the finishedAt value to set
     * @return the V1ContainerStateTerminated object itself.
     */
    public V1ContainerStateTerminated withFinishedAt(DateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the V1ContainerStateTerminated object itself.
     */
    public V1ContainerStateTerminated withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the reason value.
     *
     * @return the reason value
     */
    public String reason() {
        return this.reason;
    }

    /**
     * Set the reason value.
     *
     * @param reason the reason value to set
     * @return the V1ContainerStateTerminated object itself.
     */
    public V1ContainerStateTerminated withReason(String reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Get the signal value.
     *
     * @return the signal value
     */
    public Integer signal() {
        return this.signal;
    }

    /**
     * Set the signal value.
     *
     * @param signal the signal value to set
     * @return the V1ContainerStateTerminated object itself.
     */
    public V1ContainerStateTerminated withSignal(Integer signal) {
        this.signal = signal;
        return this;
    }

    /**
     * Get the startedAt value.
     *
     * @return the startedAt value
     */
    public DateTime startedAt() {
        return this.startedAt;
    }

    /**
     * Set the startedAt value.
     *
     * @param startedAt the startedAt value to set
     * @return the V1ContainerStateTerminated object itself.
     */
    public V1ContainerStateTerminated withStartedAt(DateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

}
