/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DownwardAPIVolumeSource represents a volume containing downward API info.
 * Downward API volumes support ownership management and SELinux relabeling.
 */
public class V1DownwardAPIVolumeSource {
    /**
     * Optional: mode bits to use on created files by default. Must be a value
     * between 0 and 0777. Defaults to 0644. Directories within the path are
     * not affected by this setting. This might be in conflict with other
     * options that affect the file mode, like fsGroup, and the result can be
     * other mode bits set.
     */
    @JsonProperty(value = "defaultMode")
    private Integer defaultMode;

    /**
     * Items is a list of downward API volume file.
     */
    @JsonProperty(value = "items")
    private List<V1DownwardAPIVolumeFile> items;

    /**
     * Get the defaultMode value.
     *
     * @return the defaultMode value
     */
    public Integer defaultMode() {
        return this.defaultMode;
    }

    /**
     * Set the defaultMode value.
     *
     * @param defaultMode the defaultMode value to set
     * @return the V1DownwardAPIVolumeSource object itself.
     */
    public V1DownwardAPIVolumeSource withDefaultMode(Integer defaultMode) {
        this.defaultMode = defaultMode;
        return this;
    }

    /**
     * Get the items value.
     *
     * @return the items value
     */
    public List<V1DownwardAPIVolumeFile> items() {
        return this.items;
    }

    /**
     * Set the items value.
     *
     * @param items the items value to set
     * @return the V1DownwardAPIVolumeSource object itself.
     */
    public V1DownwardAPIVolumeSource withItems(List<V1DownwardAPIVolumeFile> items) {
        this.items = items;
        return this;
    }

}
