/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EnvFromSource represents the source of a set of ConfigMaps.
 */
public class V1EnvFromSource {
    /**
     * The ConfigMap to select from.
     */
    @JsonProperty(value = "configMapRef")
    private V1ConfigMapEnvSource configMapRef;

    /**
     * An optional identifer to prepend to each key in the ConfigMap. Must be a
     * C_IDENTIFIER.
     */
    @JsonProperty(value = "prefix")
    private String prefix;

    /**
     * The Secret to select from.
     */
    @JsonProperty(value = "secretRef")
    private V1SecretEnvSource secretRef;

    /**
     * Get the configMapRef value.
     *
     * @return the configMapRef value
     */
    public V1ConfigMapEnvSource configMapRef() {
        return this.configMapRef;
    }

    /**
     * Set the configMapRef value.
     *
     * @param configMapRef the configMapRef value to set
     * @return the V1EnvFromSource object itself.
     */
    public V1EnvFromSource withConfigMapRef(V1ConfigMapEnvSource configMapRef) {
        this.configMapRef = configMapRef;
        return this;
    }

    /**
     * Get the prefix value.
     *
     * @return the prefix value
     */
    public String prefix() {
        return this.prefix;
    }

    /**
     * Set the prefix value.
     *
     * @param prefix the prefix value to set
     * @return the V1EnvFromSource object itself.
     */
    public V1EnvFromSource withPrefix(String prefix) {
        this.prefix = prefix;
        return this;
    }

    /**
     * Get the secretRef value.
     *
     * @return the secretRef value
     */
    public V1SecretEnvSource secretRef() {
        return this.secretRef;
    }

    /**
     * Set the secretRef value.
     *
     * @param secretRef the secretRef value to set
     * @return the V1EnvFromSource object itself.
     */
    public V1EnvFromSource withSecretRef(V1SecretEnvSource secretRef) {
        this.secretRef = secretRef;
        return this;
    }

}
