/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * EventSource contains information for an event.
 */
public class V1EventSource {
    /**
     * Component from which the event is generated.
     */
    @JsonProperty(value = "component")
    private String component;

    /**
     * Node name on which the event is generated.
     */
    @JsonProperty(value = "host")
    private String host;

    /**
     * Get the component value.
     *
     * @return the component value
     */
    public String component() {
        return this.component;
    }

    /**
     * Set the component value.
     *
     * @param component the component value to set
     * @return the V1EventSource object itself.
     */
    public V1EventSource withComponent(String component) {
        this.component = component;
        return this;
    }

    /**
     * Get the host value.
     *
     * @return the host value
     */
    public String host() {
        return this.host;
    }

    /**
     * Set the host value.
     *
     * @param host the host value to set
     * @return the V1EventSource object itself.
     */
    public V1EventSource withHost(String host) {
        this.host = host;
        return this;
    }

}
