/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Event is a report of an event somewhere in the cluster.
 */
public class V1Event {
    /**
     * APIVersion defines the versioned schema of this representation of an
     * object. Servers should convert recognized schemas to the latest internal
     * value, and may reject unrecognized values. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources.
     */
    @JsonProperty(value = "apiVersion")
    private String apiVersion;

    /**
     * The number of times this event has occurred.
     */
    @JsonProperty(value = "count")
    private Integer count;

    /**
     * The time at which the event was first recorded. (Time of server receipt
     * is in TypeMeta.).
     */
    @JsonProperty(value = "firstTimestamp")
    private DateTime firstTimestamp;

    /**
     * The object that this event is about.
     */
    @JsonProperty(value = "involvedObject", required = true)
    private V1ObjectReference involvedObject;

    /**
     * Kind is a string value representing the REST resource this object
     * represents. Servers may infer this from the endpoint the client submits
     * requests to. Cannot be updated. In CamelCase. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds.
     */
    @JsonProperty(value = "kind")
    private String kind;

    /**
     * The time at which the most recent occurrence of this event was recorded.
     */
    @JsonProperty(value = "lastTimestamp")
    private DateTime lastTimestamp;

    /**
     * A human-readable description of the status of this operation.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * Standard object's metadata. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata.
     */
    @JsonProperty(value = "metadata", required = true)
    private V1ObjectMeta metadata;

    /**
     * This should be a short, machine understandable string that gives the
     * reason for the transition into the object's current status.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /**
     * The component reporting this event. Should be a short machine
     * understandable string.
     */
    @JsonProperty(value = "source")
    private V1EventSource source;

    /**
     * Type of this event (Normal, Warning), new types could be added in the
     * future.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Get the apiVersion value.
     *
     * @return the apiVersion value
     */
    public String apiVersion() {
        return this.apiVersion;
    }

    /**
     * Set the apiVersion value.
     *
     * @param apiVersion the apiVersion value to set
     * @return the V1Event object itself.
     */
    public V1Event withApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Get the count value.
     *
     * @return the count value
     */
    public Integer count() {
        return this.count;
    }

    /**
     * Set the count value.
     *
     * @param count the count value to set
     * @return the V1Event object itself.
     */
    public V1Event withCount(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Get the firstTimestamp value.
     *
     * @return the firstTimestamp value
     */
    public DateTime firstTimestamp() {
        return this.firstTimestamp;
    }

    /**
     * Set the firstTimestamp value.
     *
     * @param firstTimestamp the firstTimestamp value to set
     * @return the V1Event object itself.
     */
    public V1Event withFirstTimestamp(DateTime firstTimestamp) {
        this.firstTimestamp = firstTimestamp;
        return this;
    }

    /**
     * Get the involvedObject value.
     *
     * @return the involvedObject value
     */
    public V1ObjectReference involvedObject() {
        return this.involvedObject;
    }

    /**
     * Set the involvedObject value.
     *
     * @param involvedObject the involvedObject value to set
     * @return the V1Event object itself.
     */
    public V1Event withInvolvedObject(V1ObjectReference involvedObject) {
        this.involvedObject = involvedObject;
        return this;
    }

    /**
     * Get the kind value.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set the kind value.
     *
     * @param kind the kind value to set
     * @return the V1Event object itself.
     */
    public V1Event withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the lastTimestamp value.
     *
     * @return the lastTimestamp value
     */
    public DateTime lastTimestamp() {
        return this.lastTimestamp;
    }

    /**
     * Set the lastTimestamp value.
     *
     * @param lastTimestamp the lastTimestamp value to set
     * @return the V1Event object itself.
     */
    public V1Event withLastTimestamp(DateTime lastTimestamp) {
        this.lastTimestamp = lastTimestamp;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the V1Event object itself.
     */
    public V1Event withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the metadata value.
     *
     * @return the metadata value
     */
    public V1ObjectMeta metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata value.
     *
     * @param metadata the metadata value to set
     * @return the V1Event object itself.
     */
    public V1Event withMetadata(V1ObjectMeta metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get the reason value.
     *
     * @return the reason value
     */
    public String reason() {
        return this.reason;
    }

    /**
     * Set the reason value.
     *
     * @param reason the reason value to set
     * @return the V1Event object itself.
     */
    public V1Event withReason(String reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Get the source value.
     *
     * @return the source value
     */
    public V1EventSource source() {
        return this.source;
    }

    /**
     * Set the source value.
     *
     * @param source the source value to set
     * @return the V1Event object itself.
     */
    public V1Event withSource(V1EventSource source) {
        this.source = source;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the V1Event object itself.
     */
    public V1Event withType(String type) {
        this.type = type;
        return this;
    }

}
