/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ExecAction describes a "run in container" action.
 */
public class V1ExecAction {
    /**
     * Command is the command line to execute inside the container, the working
     * directory for the command  is root ('/') in the container's filesystem.
     * The command is simply exec'd, it is not run inside a shell, so
     * traditional shell instructions ('|', etc) won't work. To use a shell,
     * you need to explicitly call out to that shell. Exit status of 0 is
     * treated as live/healthy and non-zero is unhealthy.
     */
    @JsonProperty(value = "command")
    private List<String> command;

    /**
     * Get the command value.
     *
     * @return the command value
     */
    public List<String> command() {
        return this.command;
    }

    /**
     * Set the command value.
     *
     * @param command the command value to set
     * @return the V1ExecAction object itself.
     */
    public V1ExecAction withCommand(List<String> command) {
        this.command = command;
        return this;
    }

}
