/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a Glusterfs mount that lasts the lifetime of a pod. Glusterfs
 * volumes do not support ownership management or SELinux relabeling.
 */
public class V1GlusterfsVolumeSource {
    /**
     * EndpointsName is the endpoint name that details Glusterfs topology. More
     * info:
     * http://releases.k8s.io/HEAD/examples/volumes/glusterfs/README.md#create-a-pod.
     */
    @JsonProperty(value = "endpoints", required = true)
    private String endpoints;

    /**
     * Path is the Glusterfs volume path. More info:
     * http://releases.k8s.io/HEAD/examples/volumes/glusterfs/README.md#create-a-pod.
     */
    @JsonProperty(value = "path", required = true)
    private String path;

    /**
     * ReadOnly here will force the Glusterfs volume to be mounted with
     * read-only permissions. Defaults to false. More info:
     * http://releases.k8s.io/HEAD/examples/volumes/glusterfs/README.md#create-a-pod.
     */
    @JsonProperty(value = "readOnly")
    private Boolean readOnly;

    /**
     * Get the endpoints value.
     *
     * @return the endpoints value
     */
    public String endpoints() {
        return this.endpoints;
    }

    /**
     * Set the endpoints value.
     *
     * @param endpoints the endpoints value to set
     * @return the V1GlusterfsVolumeSource object itself.
     */
    public V1GlusterfsVolumeSource withEndpoints(String endpoints) {
        this.endpoints = endpoints;
        return this;
    }

    /**
     * Get the path value.
     *
     * @return the path value
     */
    public String path() {
        return this.path;
    }

    /**
     * Set the path value.
     *
     * @param path the path value to set
     * @return the V1GlusterfsVolumeSource object itself.
     */
    public V1GlusterfsVolumeSource withPath(String path) {
        this.path = path;
        return this;
    }

    /**
     * Get the readOnly value.
     *
     * @return the readOnly value
     */
    public Boolean readOnly() {
        return this.readOnly;
    }

    /**
     * Set the readOnly value.
     *
     * @param readOnly the readOnly value to set
     * @return the V1GlusterfsVolumeSource object itself.
     */
    public V1GlusterfsVolumeSource withReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
        return this;
    }

}
