/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * specification of a horizontal pod autoscaler.
 */
public class V1HorizontalPodAutoscalerSpec {
    /**
     * upper limit for the number of pods that can be set by the autoscaler;
     * cannot be smaller than MinReplicas.
     */
    @JsonProperty(value = "maxReplicas", required = true)
    private int maxReplicas;

    /**
     * lower limit for the number of pods that can be set by the autoscaler,
     * default 1.
     */
    @JsonProperty(value = "minReplicas")
    private Integer minReplicas;

    /**
     * reference to scaled resource; horizontal pod autoscaler will learn the
     * current resource consumption and will set the desired number of pods by
     * using its Scale subresource.
     */
    @JsonProperty(value = "scaleTargetRef", required = true)
    private V1CrossVersionObjectReference scaleTargetRef;

    /**
     * target average CPU utilization (represented as a percentage of requested
     * CPU) over all the pods; if not specified the default autoscaling policy
     * will be used.
     */
    @JsonProperty(value = "targetCPUUtilizationPercentage")
    private Integer targetCPUUtilizationPercentage;

    /**
     * Get the maxReplicas value.
     *
     * @return the maxReplicas value
     */
    public int maxReplicas() {
        return this.maxReplicas;
    }

    /**
     * Set the maxReplicas value.
     *
     * @param maxReplicas the maxReplicas value to set
     * @return the V1HorizontalPodAutoscalerSpec object itself.
     */
    public V1HorizontalPodAutoscalerSpec withMaxReplicas(int maxReplicas) {
        this.maxReplicas = maxReplicas;
        return this;
    }

    /**
     * Get the minReplicas value.
     *
     * @return the minReplicas value
     */
    public Integer minReplicas() {
        return this.minReplicas;
    }

    /**
     * Set the minReplicas value.
     *
     * @param minReplicas the minReplicas value to set
     * @return the V1HorizontalPodAutoscalerSpec object itself.
     */
    public V1HorizontalPodAutoscalerSpec withMinReplicas(Integer minReplicas) {
        this.minReplicas = minReplicas;
        return this;
    }

    /**
     * Get the scaleTargetRef value.
     *
     * @return the scaleTargetRef value
     */
    public V1CrossVersionObjectReference scaleTargetRef() {
        return this.scaleTargetRef;
    }

    /**
     * Set the scaleTargetRef value.
     *
     * @param scaleTargetRef the scaleTargetRef value to set
     * @return the V1HorizontalPodAutoscalerSpec object itself.
     */
    public V1HorizontalPodAutoscalerSpec withScaleTargetRef(V1CrossVersionObjectReference scaleTargetRef) {
        this.scaleTargetRef = scaleTargetRef;
        return this;
    }

    /**
     * Get the targetCPUUtilizationPercentage value.
     *
     * @return the targetCPUUtilizationPercentage value
     */
    public Integer targetCPUUtilizationPercentage() {
        return this.targetCPUUtilizationPercentage;
    }

    /**
     * Set the targetCPUUtilizationPercentage value.
     *
     * @param targetCPUUtilizationPercentage the targetCPUUtilizationPercentage value to set
     * @return the V1HorizontalPodAutoscalerSpec object itself.
     */
    public V1HorizontalPodAutoscalerSpec withTargetCPUUtilizationPercentage(Integer targetCPUUtilizationPercentage) {
        this.targetCPUUtilizationPercentage = targetCPUUtilizationPercentage;
        return this;
    }

}
