/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * HTTPHeader describes a custom header to be used in HTTP probes.
 */
public class V1HTTPHeader {
    /**
     * The header field name.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The header field value.
     */
    @JsonProperty(value = "value", required = true)
    private String value;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V1HTTPHeader object itself.
     */
    public V1HTTPHeader withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the V1HTTPHeader object itself.
     */
    public V1HTTPHeader withValue(String value) {
        this.value = value;
        return this;
    }

}
