/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * HTTPGetAction describes an action based on HTTP Get requests.
 */
public class V1HTTPGetAction {
    /**
     * Host name to connect to, defaults to the pod IP. You probably want to
     * set "Host" in httpHeaders instead.
     */
    @JsonProperty(value = "host")
    private String host;

    /**
     * Custom headers to set in the request. HTTP allows repeated headers.
     */
    @JsonProperty(value = "httpHeaders")
    private List<V1HTTPHeader> httpHeaders;

    /**
     * Path to access on the HTTP server.
     */
    @JsonProperty(value = "path")
    private String path;

    /**
     * Name or number of the port to access on the container. Number must be in
     * the range 1 to 65535. Name must be an IANA_SVC_NAME.
     */
    @JsonProperty(value = "port", required = true)
    private String port;

    /**
     * Scheme to use for connecting to the host. Defaults to HTTP.
     */
    @JsonProperty(value = "scheme")
    private String scheme;

    /**
     * Get the host value.
     *
     * @return the host value
     */
    public String host() {
        return this.host;
    }

    /**
     * Set the host value.
     *
     * @param host the host value to set
     * @return the V1HTTPGetAction object itself.
     */
    public V1HTTPGetAction withHost(String host) {
        this.host = host;
        return this;
    }

    /**
     * Get the httpHeaders value.
     *
     * @return the httpHeaders value
     */
    public List<V1HTTPHeader> httpHeaders() {
        return this.httpHeaders;
    }

    /**
     * Set the httpHeaders value.
     *
     * @param httpHeaders the httpHeaders value to set
     * @return the V1HTTPGetAction object itself.
     */
    public V1HTTPGetAction withHttpHeaders(List<V1HTTPHeader> httpHeaders) {
        this.httpHeaders = httpHeaders;
        return this;
    }

    /**
     * Get the path value.
     *
     * @return the path value
     */
    public String path() {
        return this.path;
    }

    /**
     * Set the path value.
     *
     * @param path the path value to set
     * @return the V1HTTPGetAction object itself.
     */
    public V1HTTPGetAction withPath(String path) {
        this.path = path;
        return this;
    }

    /**
     * Get the port value.
     *
     * @return the port value
     */
    public String port() {
        return this.port;
    }

    /**
     * Set the port value.
     *
     * @param port the port value to set
     * @return the V1HTTPGetAction object itself.
     */
    public V1HTTPGetAction withPort(String port) {
        this.port = port;
        return this;
    }

    /**
     * Get the scheme value.
     *
     * @return the scheme value
     */
    public String scheme() {
        return this.scheme;
    }

    /**
     * Set the scheme value.
     *
     * @param scheme the scheme value to set
     * @return the V1HTTPGetAction object itself.
     */
    public V1HTTPGetAction withScheme(String scheme) {
        this.scheme = scheme;
        return this;
    }

}
