/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * JobCondition describes current state of a job.
 */
public class V1JobCondition {
    /**
     * Last time the condition was checked.
     */
    @JsonProperty(value = "lastProbeTime")
    private DateTime lastProbeTime;

    /**
     * Last time the condition transit from one status to another.
     */
    @JsonProperty(value = "lastTransitionTime")
    private DateTime lastTransitionTime;

    /**
     * Human readable message indicating details about last transition.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * (brief) reason for the condition's last transition.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /**
     * Status of the condition, one of True, False, Unknown.
     */
    @JsonProperty(value = "status", required = true)
    private String status;

    /**
     * Type of job condition, Complete or Failed.
     */
    @JsonProperty(value = "type", required = true)
    private String type;

    /**
     * Get the lastProbeTime value.
     *
     * @return the lastProbeTime value
     */
    public DateTime lastProbeTime() {
        return this.lastProbeTime;
    }

    /**
     * Set the lastProbeTime value.
     *
     * @param lastProbeTime the lastProbeTime value to set
     * @return the V1JobCondition object itself.
     */
    public V1JobCondition withLastProbeTime(DateTime lastProbeTime) {
        this.lastProbeTime = lastProbeTime;
        return this;
    }

    /**
     * Get the lastTransitionTime value.
     *
     * @return the lastTransitionTime value
     */
    public DateTime lastTransitionTime() {
        return this.lastTransitionTime;
    }

    /**
     * Set the lastTransitionTime value.
     *
     * @param lastTransitionTime the lastTransitionTime value to set
     * @return the V1JobCondition object itself.
     */
    public V1JobCondition withLastTransitionTime(DateTime lastTransitionTime) {
        this.lastTransitionTime = lastTransitionTime;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the V1JobCondition object itself.
     */
    public V1JobCondition withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the reason value.
     *
     * @return the reason value
     */
    public String reason() {
        return this.reason;
    }

    /**
     * Set the reason value.
     *
     * @param reason the reason value to set
     * @return the V1JobCondition object itself.
     */
    public V1JobCondition withReason(String reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Get the status value.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the status value.
     *
     * @param status the status value to set
     * @return the V1JobCondition object itself.
     */
    public V1JobCondition withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the V1JobCondition object itself.
     */
    public V1JobCondition withType(String type) {
        this.type = type;
        return this;
    }

}
