/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import org.joda.time.DateTime;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * JobStatus represents the current state of a Job.
 */
public class V1JobStatus {
    /**
     * Active is the number of actively running pods.
     */
    @JsonProperty(value = "active")
    private Integer active;

    /**
     * CompletionTime represents time when the job was completed. It is not
     * guaranteed to be set in happens-before order across separate operations.
     * It is represented in RFC3339 form and is in UTC.
     */
    @JsonProperty(value = "completionTime")
    private DateTime completionTime;

    /**
     * Conditions represent the latest available observations of an object's
     * current state. More info: http://kubernetes.io/docs/user-guide/jobs.
     */
    @JsonProperty(value = "conditions")
    private List<V1JobCondition> conditions;

    /**
     * Failed is the number of pods which reached Phase Failed.
     */
    @JsonProperty(value = "failed")
    private Integer failed;

    /**
     * StartTime represents time when the job was acknowledged by the Job
     * Manager. It is not guaranteed to be set in happens-before order across
     * separate operations. It is represented in RFC3339 form and is in UTC.
     */
    @JsonProperty(value = "startTime")
    private DateTime startTime;

    /**
     * Succeeded is the number of pods which reached Phase Succeeded.
     */
    @JsonProperty(value = "succeeded")
    private Integer succeeded;

    /**
     * Get the active value.
     *
     * @return the active value
     */
    public Integer active() {
        return this.active;
    }

    /**
     * Set the active value.
     *
     * @param active the active value to set
     * @return the V1JobStatus object itself.
     */
    public V1JobStatus withActive(Integer active) {
        this.active = active;
        return this;
    }

    /**
     * Get the completionTime value.
     *
     * @return the completionTime value
     */
    public DateTime completionTime() {
        return this.completionTime;
    }

    /**
     * Set the completionTime value.
     *
     * @param completionTime the completionTime value to set
     * @return the V1JobStatus object itself.
     */
    public V1JobStatus withCompletionTime(DateTime completionTime) {
        this.completionTime = completionTime;
        return this;
    }

    /**
     * Get the conditions value.
     *
     * @return the conditions value
     */
    public List<V1JobCondition> conditions() {
        return this.conditions;
    }

    /**
     * Set the conditions value.
     *
     * @param conditions the conditions value to set
     * @return the V1JobStatus object itself.
     */
    public V1JobStatus withConditions(List<V1JobCondition> conditions) {
        this.conditions = conditions;
        return this;
    }

    /**
     * Get the failed value.
     *
     * @return the failed value
     */
    public Integer failed() {
        return this.failed;
    }

    /**
     * Set the failed value.
     *
     * @param failed the failed value to set
     * @return the V1JobStatus object itself.
     */
    public V1JobStatus withFailed(Integer failed) {
        this.failed = failed;
        return this;
    }

    /**
     * Get the startTime value.
     *
     * @return the startTime value
     */
    public DateTime startTime() {
        return this.startTime;
    }

    /**
     * Set the startTime value.
     *
     * @param startTime the startTime value to set
     * @return the V1JobStatus object itself.
     */
    public V1JobStatus withStartTime(DateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Get the succeeded value.
     *
     * @return the succeeded value
     */
    public Integer succeeded() {
        return this.succeeded;
    }

    /**
     * Set the succeeded value.
     *
     * @param succeeded the succeeded value to set
     * @return the V1JobStatus object itself.
     */
    public V1JobStatus withSucceeded(Integer succeeded) {
        this.succeeded = succeeded;
        return this;
    }

}
