/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LoadBalancerIngress represents the status of a load-balancer ingress point:
 * traffic intended for the service should be sent to an ingress point.
 */
public class V1LoadBalancerIngress {
    /**
     * Hostname is set for load-balancer ingress points that are DNS based
     * (typically AWS load-balancers).
     */
    @JsonProperty(value = "hostname")
    private String hostname;

    /**
     * IP is set for load-balancer ingress points that are IP based (typically
     * GCE or OpenStack load-balancers).
     */
    @JsonProperty(value = "ip")
    private String ip;

    /**
     * Get the hostname value.
     *
     * @return the hostname value
     */
    public String hostname() {
        return this.hostname;
    }

    /**
     * Set the hostname value.
     *
     * @param hostname the hostname value to set
     * @return the V1LoadBalancerIngress object itself.
     */
    public V1LoadBalancerIngress withHostname(String hostname) {
        this.hostname = hostname;
        return this;
    }

    /**
     * Get the ip value.
     *
     * @return the ip value
     */
    public String ip() {
        return this.ip;
    }

    /**
     * Set the ip value.
     *
     * @param ip the ip value to set
     * @return the V1LoadBalancerIngress object itself.
     */
    public V1LoadBalancerIngress withIp(String ip) {
        this.ip = ip;
        return this;
    }

}
