/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NamespaceStatus is information about the current status of a Namespace.
 */
public class V1NamespaceStatus {
    /**
     * Phase is the current lifecycle phase of the namespace. More info:
     * http://releases.k8s.io/HEAD/docs/design/namespaces.md#phases.
     */
    @JsonProperty(value = "phase")
    private String phase;

    /**
     * Get the phase value.
     *
     * @return the phase value
     */
    public String phase() {
        return this.phase;
    }

    /**
     * Set the phase value.
     *
     * @param phase the phase value to set
     * @return the V1NamespaceStatus object itself.
     */
    public V1NamespaceStatus withPhase(String phase) {
        this.phase = phase;
        return this;
    }

}
