/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NamespaceSpec describes the attributes on a Namespace.
 */
public class V1NamespaceSpec {
    /**
     * Finalizers is an opaque list of values that must be empty to permanently
     * remove object from storage. More info:
     * http://releases.k8s.io/HEAD/docs/design/namespaces.md#finalizers.
     */
    @JsonProperty(value = "finalizers")
    private List<String> finalizers;

    /**
     * Get the finalizers value.
     *
     * @return the finalizers value
     */
    public List<String> finalizers() {
        return this.finalizers;
    }

    /**
     * Set the finalizers value.
     *
     * @param finalizers the finalizers value to set
     * @return the V1NamespaceSpec object itself.
     */
    public V1NamespaceSpec withFinalizers(List<String> finalizers) {
        this.finalizers = finalizers;
        return this;
    }

}
