/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * NodeAddress contains information for the node's address.
 */
public class V1NodeAddress {
    /**
     * The node address.
     */
    @JsonProperty(value = "address", required = true)
    private String address;

    /**
     * Node address type, one of Hostname, ExternalIP or InternalIP.
     */
    @JsonProperty(value = "type", required = true)
    private String type;

    /**
     * Get the address value.
     *
     * @return the address value
     */
    public String address() {
        return this.address;
    }

    /**
     * Set the address value.
     *
     * @param address the address value to set
     * @return the V1NodeAddress object itself.
     */
    public V1NodeAddress withAddress(String address) {
        this.address = address;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the V1NodeAddress object itself.
     */
    public V1NodeAddress withType(String type) {
        this.type = type;
        return this;
    }

}
