/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A node selector represents the union of the results of one or more label
 * queries over a set of nodes; that is, it represents the OR of the selectors
 * represented by the node selector terms.
 */
public class V1NodeSelector {
    /**
     * Required. A list of node selector terms. The terms are ORed.
     */
    @JsonProperty(value = "nodeSelectorTerms", required = true)
    private List<V1NodeSelectorTerm> nodeSelectorTerms;

    /**
     * Get the nodeSelectorTerms value.
     *
     * @return the nodeSelectorTerms value
     */
    public List<V1NodeSelectorTerm> nodeSelectorTerms() {
        return this.nodeSelectorTerms;
    }

    /**
     * Set the nodeSelectorTerms value.
     *
     * @param nodeSelectorTerms the nodeSelectorTerms value to set
     * @return the V1NodeSelector object itself.
     */
    public V1NodeSelector withNodeSelectorTerms(List<V1NodeSelectorTerm> nodeSelectorTerms) {
        this.nodeSelectorTerms = nodeSelectorTerms;
        return this;
    }

}
