/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ObjectReference contains enough information to let you inspect or modify the
 * referred object.
 */
public class V1ObjectReference {
    /**
     * API version of the referent.
     */
    @JsonProperty(value = "apiVersion")
    private String apiVersion;

    /**
     * If referring to a piece of an object instead of an entire object, this
     * string should contain a valid JSON/Go field access statement, such as
     * desiredState.manifest.containers[2]. For example, if the object
     * reference is to a container within a pod, this would take on a value
     * like: "spec.containers{name}" (where "name" refers to the name of the
     * container that triggered the event) or if no container name is specified
     * "spec.containers[2]" (container with index 2 in this pod). This syntax
     * is chosen only to have some well-defined way of referencing a part of an
     * object.
     */
    @JsonProperty(value = "fieldPath")
    private String fieldPath;

    /**
     * Kind of the referent. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds.
     */
    @JsonProperty(value = "kind")
    private String kind;

    /**
     * Name of the referent. More info:
     * http://kubernetes.io/docs/user-guide/identifiers#names.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Namespace of the referent. More info:
     * http://kubernetes.io/docs/user-guide/namespaces.
     */
    @JsonProperty(value = "namespace")
    private String namespace;

    /**
     * Specific resourceVersion to which this reference is made, if any. More
     * info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#concurrency-control-and-consistency.
     */
    @JsonProperty(value = "resourceVersion")
    private String resourceVersion;

    /**
     * UID of the referent. More info:
     * http://kubernetes.io/docs/user-guide/identifiers#uids.
     */
    @JsonProperty(value = "uid")
    private String uid;

    /**
     * Get the apiVersion value.
     *
     * @return the apiVersion value
     */
    public String apiVersion() {
        return this.apiVersion;
    }

    /**
     * Set the apiVersion value.
     *
     * @param apiVersion the apiVersion value to set
     * @return the V1ObjectReference object itself.
     */
    public V1ObjectReference withApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Get the fieldPath value.
     *
     * @return the fieldPath value
     */
    public String fieldPath() {
        return this.fieldPath;
    }

    /**
     * Set the fieldPath value.
     *
     * @param fieldPath the fieldPath value to set
     * @return the V1ObjectReference object itself.
     */
    public V1ObjectReference withFieldPath(String fieldPath) {
        this.fieldPath = fieldPath;
        return this;
    }

    /**
     * Get the kind value.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set the kind value.
     *
     * @param kind the kind value to set
     * @return the V1ObjectReference object itself.
     */
    public V1ObjectReference withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V1ObjectReference object itself.
     */
    public V1ObjectReference withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the namespace value.
     *
     * @return the namespace value
     */
    public String namespace() {
        return this.namespace;
    }

    /**
     * Set the namespace value.
     *
     * @param namespace the namespace value to set
     * @return the V1ObjectReference object itself.
     */
    public V1ObjectReference withNamespace(String namespace) {
        this.namespace = namespace;
        return this;
    }

    /**
     * Get the resourceVersion value.
     *
     * @return the resourceVersion value
     */
    public String resourceVersion() {
        return this.resourceVersion;
    }

    /**
     * Set the resourceVersion value.
     *
     * @param resourceVersion the resourceVersion value to set
     * @return the V1ObjectReference object itself.
     */
    public V1ObjectReference withResourceVersion(String resourceVersion) {
        this.resourceVersion = resourceVersion;
        return this;
    }

    /**
     * Get the uid value.
     *
     * @return the uid value
     */
    public String uid() {
        return this.uid;
    }

    /**
     * Set the uid value.
     *
     * @param uid the uid value to set
     * @return the V1ObjectReference object itself.
     */
    public V1ObjectReference withUid(String uid) {
        this.uid = uid;
        return this;
    }

}
