/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ObjectFieldSelector selects an APIVersioned field of an object.
 */
public class V1ObjectFieldSelector {
    /**
     * Version of the schema the FieldPath is written in terms of, defaults to
     * "v1".
     */
    @JsonProperty(value = "apiVersion")
    private String apiVersion;

    /**
     * Path of the field to select in the specified API version.
     */
    @JsonProperty(value = "fieldPath", required = true)
    private String fieldPath;

    /**
     * Get the apiVersion value.
     *
     * @return the apiVersion value
     */
    public String apiVersion() {
        return this.apiVersion;
    }

    /**
     * Set the apiVersion value.
     *
     * @param apiVersion the apiVersion value to set
     * @return the V1ObjectFieldSelector object itself.
     */
    public V1ObjectFieldSelector withApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Get the fieldPath value.
     *
     * @return the fieldPath value
     */
    public String fieldPath() {
        return this.fieldPath;
    }

    /**
     * Set the fieldPath value.
     *
     * @param fieldPath the fieldPath value to set
     * @return the V1ObjectFieldSelector object itself.
     */
    public V1ObjectFieldSelector withFieldPath(String fieldPath) {
        this.fieldPath = fieldPath;
        return this;
    }

}
