/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PersistentVolumeClaimStatus is the current status of a persistent volume
 * claim.
 */
public class V1PersistentVolumeClaimStatus {
    /**
     * AccessModes contains the actual access modes the volume backing the PVC
     * has. More info:
     * http://kubernetes.io/docs/user-guide/persistent-volumes#access-modes-1.
     */
    @JsonProperty(value = "accessModes")
    private List<String> accessModes;

    /**
     * Represents the actual resources of the underlying volume.
     */
    @JsonProperty(value = "capacity")
    private Map<String, String> capacity;

    /**
     * Phase represents the current phase of PersistentVolumeClaim.
     */
    @JsonProperty(value = "phase")
    private String phase;

    /**
     * Get the accessModes value.
     *
     * @return the accessModes value
     */
    public List<String> accessModes() {
        return this.accessModes;
    }

    /**
     * Set the accessModes value.
     *
     * @param accessModes the accessModes value to set
     * @return the V1PersistentVolumeClaimStatus object itself.
     */
    public V1PersistentVolumeClaimStatus withAccessModes(List<String> accessModes) {
        this.accessModes = accessModes;
        return this;
    }

    /**
     * Get the capacity value.
     *
     * @return the capacity value
     */
    public Map<String, String> capacity() {
        return this.capacity;
    }

    /**
     * Set the capacity value.
     *
     * @param capacity the capacity value to set
     * @return the V1PersistentVolumeClaimStatus object itself.
     */
    public V1PersistentVolumeClaimStatus withCapacity(Map<String, String> capacity) {
        this.capacity = capacity;
        return this;
    }

    /**
     * Get the phase value.
     *
     * @return the phase value
     */
    public String phase() {
        return this.phase;
    }

    /**
     * Set the phase value.
     *
     * @param phase the phase value to set
     * @return the V1PersistentVolumeClaimStatus object itself.
     */
    public V1PersistentVolumeClaimStatus withPhase(String phase) {
        this.phase = phase;
        return this;
    }

}
