/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PersistentVolumeStatus is the current status of a persistent volume.
 */
public class V1PersistentVolumeStatus {
    /**
     * A human-readable message indicating details about why the volume is in
     * this state.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * Phase indicates if a volume is available, bound to a claim, or released
     * by a claim. More info:
     * http://kubernetes.io/docs/user-guide/persistent-volumes#phase.
     */
    @JsonProperty(value = "phase")
    private String phase;

    /**
     * Reason is a brief CamelCase string that describes any failure and is
     * meant for machine parsing and tidy display in the CLI.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the V1PersistentVolumeStatus object itself.
     */
    public V1PersistentVolumeStatus withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the phase value.
     *
     * @return the phase value
     */
    public String phase() {
        return this.phase;
    }

    /**
     * Set the phase value.
     *
     * @param phase the phase value to set
     * @return the V1PersistentVolumeStatus object itself.
     */
    public V1PersistentVolumeStatus withPhase(String phase) {
        this.phase = phase;
        return this;
    }

    /**
     * Get the reason value.
     *
     * @return the reason value
     */
    public String reason() {
        return this.reason;
    }

    /**
     * Set the reason value.
     *
     * @param reason the reason value to set
     * @return the V1PersistentVolumeStatus object itself.
     */
    public V1PersistentVolumeStatus withReason(String reason) {
        this.reason = reason;
        return this;
    }

}
