/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PortworxVolumeSource represents a Portworx volume resource.
 */
public class V1PortworxVolumeSource {
    /**
     * FSType represents the filesystem type to mount Must be a filesystem type
     * supported by the host operating system. Ex. "ext4", "xfs". Implicitly
     * inferred to be "ext4" if unspecified.
     */
    @JsonProperty(value = "fsType")
    private String fsType;

    /**
     * Defaults to false (read/write). ReadOnly here will force the ReadOnly
     * setting in VolumeMounts.
     */
    @JsonProperty(value = "readOnly")
    private Boolean readOnly;

    /**
     * VolumeID uniquely identifies a Portworx volume.
     */
    @JsonProperty(value = "volumeID", required = true)
    private String volumeID;

    /**
     * Get the fsType value.
     *
     * @return the fsType value
     */
    public String fsType() {
        return this.fsType;
    }

    /**
     * Set the fsType value.
     *
     * @param fsType the fsType value to set
     * @return the V1PortworxVolumeSource object itself.
     */
    public V1PortworxVolumeSource withFsType(String fsType) {
        this.fsType = fsType;
        return this;
    }

    /**
     * Get the readOnly value.
     *
     * @return the readOnly value
     */
    public Boolean readOnly() {
        return this.readOnly;
    }

    /**
     * Set the readOnly value.
     *
     * @param readOnly the readOnly value to set
     * @return the V1PortworxVolumeSource object itself.
     */
    public V1PortworxVolumeSource withReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get the volumeID value.
     *
     * @return the volumeID value
     */
    public String volumeID() {
        return this.volumeID;
    }

    /**
     * Set the volumeID value.
     *
     * @param volumeID the volumeID value to set
     * @return the V1PortworxVolumeSource object itself.
     */
    public V1PortworxVolumeSource withVolumeID(String volumeID) {
        this.volumeID = volumeID;
        return this;
    }

}
