/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An empty preferred scheduling term matches all objects with implicit weight
 * 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects
 * (i.e. is also a no-op).
 */
public class V1PreferredSchedulingTerm {
    /**
     * A node selector term, associated with the corresponding weight.
     */
    @JsonProperty(value = "preference", required = true)
    private V1NodeSelectorTerm preference;

    /**
     * Weight associated with matching the corresponding nodeSelectorTerm, in
     * the range 1-100.
     */
    @JsonProperty(value = "weight", required = true)
    private int weight;

    /**
     * Get the preference value.
     *
     * @return the preference value
     */
    public V1NodeSelectorTerm preference() {
        return this.preference;
    }

    /**
     * Set the preference value.
     *
     * @param preference the preference value to set
     * @return the V1PreferredSchedulingTerm object itself.
     */
    public V1PreferredSchedulingTerm withPreference(V1NodeSelectorTerm preference) {
        this.preference = preference;
        return this;
    }

    /**
     * Get the weight value.
     *
     * @return the weight value
     */
    public int weight() {
        return this.weight;
    }

    /**
     * Set the weight value.
     *
     * @param weight the weight value to set
     * @return the V1PreferredSchedulingTerm object itself.
     */
    public V1PreferredSchedulingTerm withWeight(int weight) {
        this.weight = weight;
        return this;
    }

}
