/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a projected volume source.
 */
public class V1ProjectedVolumeSource {
    /**
     * Mode bits to use on created files by default. Must be a value between 0
     * and 0777. Directories within the path are not affected by this setting.
     * This might be in conflict with other options that affect the file mode,
     * like fsGroup, and the result can be other mode bits set.
     */
    @JsonProperty(value = "defaultMode")
    private Integer defaultMode;

    /**
     * list of volume projections.
     */
    @JsonProperty(value = "sources", required = true)
    private List<V1VolumeProjection> sources;

    /**
     * Get the defaultMode value.
     *
     * @return the defaultMode value
     */
    public Integer defaultMode() {
        return this.defaultMode;
    }

    /**
     * Set the defaultMode value.
     *
     * @param defaultMode the defaultMode value to set
     * @return the V1ProjectedVolumeSource object itself.
     */
    public V1ProjectedVolumeSource withDefaultMode(Integer defaultMode) {
        this.defaultMode = defaultMode;
        return this;
    }

    /**
     * Get the sources value.
     *
     * @return the sources value
     */
    public List<V1VolumeProjection> sources() {
        return this.sources;
    }

    /**
     * Set the sources value.
     *
     * @param sources the sources value to set
     * @return the V1ProjectedVolumeSource object itself.
     */
    public V1ProjectedVolumeSource withSources(List<V1VolumeProjection> sources) {
        this.sources = sources;
        return this;
    }

}
