/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ResourceFieldSelector represents container resources (cpu, memory) and their
 * output format.
 */
public class V1ResourceFieldSelector {
    /**
     * Container name: required for volumes, optional for env vars.
     */
    @JsonProperty(value = "containerName")
    private String containerName;

    /**
     * Specifies the output format of the exposed resources, defaults to "1".
     */
    @JsonProperty(value = "divisor")
    private String divisor;

    /**
     * Required: resource to select.
     */
    @JsonProperty(value = "resource", required = true)
    private String resource;

    /**
     * Get the containerName value.
     *
     * @return the containerName value
     */
    public String containerName() {
        return this.containerName;
    }

    /**
     * Set the containerName value.
     *
     * @param containerName the containerName value to set
     * @return the V1ResourceFieldSelector object itself.
     */
    public V1ResourceFieldSelector withContainerName(String containerName) {
        this.containerName = containerName;
        return this;
    }

    /**
     * Get the divisor value.
     *
     * @return the divisor value
     */
    public String divisor() {
        return this.divisor;
    }

    /**
     * Set the divisor value.
     *
     * @param divisor the divisor value to set
     * @return the V1ResourceFieldSelector object itself.
     */
    public V1ResourceFieldSelector withDivisor(String divisor) {
        this.divisor = divisor;
        return this;
    }

    /**
     * Get the resource value.
     *
     * @return the resource value
     */
    public String resource() {
        return this.resource;
    }

    /**
     * Set the resource value.
     *
     * @param resource the resource value to set
     * @return the V1ResourceFieldSelector object itself.
     */
    public V1ResourceFieldSelector withResource(String resource) {
        this.resource = resource;
        return this;
    }

}
