/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SecretEnvSource selects a Secret to populate the environment variables with.
 *
 * The contents of the target Secret's Data field will represent the key-value
 * pairs as environment variables.
 */
public class V1SecretEnvSource {
    /**
     * Name of the referent. More info:
     * http://kubernetes.io/docs/user-guide/identifiers#names.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Specify whether the Secret must be defined.
     */
    @JsonProperty(value = "optional")
    private Boolean optional;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V1SecretEnvSource object itself.
     */
    public V1SecretEnvSource withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the optional value.
     *
     * @return the optional value
     */
    public Boolean optional() {
        return this.optional;
    }

    /**
     * Set the optional value.
     *
     * @param optional the optional value to set
     * @return the V1SecretEnvSource object itself.
     */
    public V1SecretEnvSource withOptional(Boolean optional) {
        this.optional = optional;
        return this;
    }

}
