/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SecretKeySelector selects a key of a Secret.
 */
public class V1SecretKeySelector {
    /**
     * The key of the secret to select from.  Must be a valid secret key.
     */
    @JsonProperty(value = "key", required = true)
    private String key;

    /**
     * Name of the referent. More info:
     * http://kubernetes.io/docs/user-guide/identifiers#names.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Specify whether the Secret or it's key must be defined.
     */
    @JsonProperty(value = "optional")
    private Boolean optional;

    /**
     * Get the key value.
     *
     * @return the key value
     */
    public String key() {
        return this.key;
    }

    /**
     * Set the key value.
     *
     * @param key the key value to set
     * @return the V1SecretKeySelector object itself.
     */
    public V1SecretKeySelector withKey(String key) {
        this.key = key;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V1SecretKeySelector object itself.
     */
    public V1SecretKeySelector withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the optional value.
     *
     * @return the optional value
     */
    public Boolean optional() {
        return this.optional;
    }

    /**
     * Set the optional value.
     *
     * @param optional the optional value to set
     * @return the V1SecretKeySelector object itself.
     */
    public V1SecretKeySelector withOptional(Boolean optional) {
        this.optional = optional;
        return this;
    }

}
