/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * TCPSocketAction describes an action based on opening a socket.
 */
public class V1TCPSocketAction {
    /**
     * Number or name of the port to access on the container. Number must be in
     * the range 1 to 65535. Name must be an IANA_SVC_NAME.
     */
    @JsonProperty(value = "port", required = true)
    private String port;

    /**
     * Get the port value.
     *
     * @return the port value
     */
    public String port() {
        return this.port;
    }

    /**
     * Set the port value.
     *
     * @param port the port value to set
     * @return the V1TCPSocketAction object itself.
     */
    public V1TCPSocketAction withPort(String port) {
        this.port = port;
        return this;
    }

}
