/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a vSphere volume resource.
 */
public class V1VsphereVirtualDiskVolumeSource {
    /**
     * Filesystem type to mount. Must be a filesystem type supported by the
     * host operating system. Ex. "ext4", "xfs", "ntfs". Implicitly inferred to
     * be "ext4" if unspecified.
     */
    @JsonProperty(value = "fsType")
    private String fsType;

    /**
     * Path that identifies vSphere volume vmdk.
     */
    @JsonProperty(value = "volumePath", required = true)
    private String volumePath;

    /**
     * Get the fsType value.
     *
     * @return the fsType value
     */
    public String fsType() {
        return this.fsType;
    }

    /**
     * Set the fsType value.
     *
     * @param fsType the fsType value to set
     * @return the V1VsphereVirtualDiskVolumeSource object itself.
     */
    public V1VsphereVirtualDiskVolumeSource withFsType(String fsType) {
        this.fsType = fsType;
        return this;
    }

    /**
     * Get the volumePath value.
     *
     * @return the volumePath value
     */
    public String volumePath() {
        return this.volumePath;
    }

    /**
     * Set the volumePath value.
     *
     * @param volumePath the volumePath value to set
     * @return the V1VsphereVirtualDiskVolumeSource object itself.
     */
    public V1VsphereVirtualDiskVolumeSource withVolumePath(String volumePath) {
        this.volumePath = volumePath;
        return this;
    }

}
