/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CrossVersionObjectReference contains enough information to let you identify
 * the referred resource.
 */
public class V2alpha1CrossVersionObjectReference {
    /**
     * API version of the referent.
     */
    @JsonProperty(value = "apiVersion")
    private String apiVersion;

    /**
     * Kind of the referent; More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds".
     */
    @JsonProperty(value = "kind", required = true)
    private String kind;

    /**
     * Name of the referent; More info:
     * http://kubernetes.io/docs/user-guide/identifiers#names.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * Get the apiVersion value.
     *
     * @return the apiVersion value
     */
    public String apiVersion() {
        return this.apiVersion;
    }

    /**
     * Set the apiVersion value.
     *
     * @param apiVersion the apiVersion value to set
     * @return the V2alpha1CrossVersionObjectReference object itself.
     */
    public V2alpha1CrossVersionObjectReference withApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Get the kind value.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set the kind value.
     *
     * @param kind the kind value to set
     * @return the V2alpha1CrossVersionObjectReference object itself.
     */
    public V2alpha1CrossVersionObjectReference withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V2alpha1CrossVersionObjectReference object itself.
     */
    public V2alpha1CrossVersionObjectReference withName(String name) {
        this.name = name;
        return this;
    }

}
