/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * JobTemplateSpec describes the data a Job should have when created from a
 * template.
 */
public class V2alpha1JobTemplateSpec {
    /**
     * Standard object's metadata of the jobs created from this template. More
     * info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata.
     */
    @JsonProperty(value = "metadata")
    private V1ObjectMeta metadata;

    /**
     * Specification of the desired behavior of the job. More info:
     * http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#spec-and-status.
     */
    @JsonProperty(value = "spec")
    private V1JobSpec spec;

    /**
     * Get the metadata value.
     *
     * @return the metadata value
     */
    public V1ObjectMeta metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata value.
     *
     * @param metadata the metadata value to set
     * @return the V2alpha1JobTemplateSpec object itself.
     */
    public V2alpha1JobTemplateSpec withMetadata(V1ObjectMeta metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get the spec value.
     *
     * @return the spec value
     */
    public V1JobSpec spec() {
        return this.spec;
    }

    /**
     * Set the spec value.
     *
     * @param spec the spec value to set
     * @return the V2alpha1JobTemplateSpec object itself.
     */
    public V2alpha1JobTemplateSpec withSpec(V1JobSpec spec) {
        this.spec = spec;
        return this;
    }

}
