/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ResourceMetricStatus indicates the current value of a resource metric known
 * to Kubernetes, as specified in requests and limits, describing each pod in
 * the current scale target (e.g. CPU or memory).  Such metrics are built in to
 * Kubernetes, and have special scaling options on top of those available to
 * normal per-pod metrics using the "pods" source.
 */
public class V2alpha1ResourceMetricStatus {
    /**
     * currentAverageUtilization is the current value of the average of the
     * resource metric across all relevant pods, represented as a percentage of
     * the requested value of the resource for the pods.  It will only be
     * present if `targetAverageValue` was set in the corresponding metric
     * specification.
     */
    @JsonProperty(value = "currentAverageUtilization")
    private Integer currentAverageUtilization;

    /**
     * currentAverageValue is the the current value of the average of the
     * resource metric across all relevant pods, as a raw value (instead of as
     * a percentage of the request), similar to the "pods" metric source type.
     * It will always be set, regardless of the corresponding metric
     * specification.
     */
    @JsonProperty(value = "currentAverageValue", required = true)
    private String currentAverageValue;

    /**
     * name is the name of the resource in question.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * Get the currentAverageUtilization value.
     *
     * @return the currentAverageUtilization value
     */
    public Integer currentAverageUtilization() {
        return this.currentAverageUtilization;
    }

    /**
     * Set the currentAverageUtilization value.
     *
     * @param currentAverageUtilization the currentAverageUtilization value to set
     * @return the V2alpha1ResourceMetricStatus object itself.
     */
    public V2alpha1ResourceMetricStatus withCurrentAverageUtilization(Integer currentAverageUtilization) {
        this.currentAverageUtilization = currentAverageUtilization;
        return this;
    }

    /**
     * Get the currentAverageValue value.
     *
     * @return the currentAverageValue value
     */
    public String currentAverageValue() {
        return this.currentAverageValue;
    }

    /**
     * Set the currentAverageValue value.
     *
     * @param currentAverageValue the currentAverageValue value to set
     * @return the V2alpha1ResourceMetricStatus object itself.
     */
    public V2alpha1ResourceMetricStatus withCurrentAverageValue(String currentAverageValue) {
        this.currentAverageValue = currentAverageValue;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the V2alpha1ResourceMetricStatus object itself.
     */
    public V2alpha1ResourceMetricStatus withName(String name) {
        this.name = name;
        return this;
    }

}
