/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PodsMetricStatus indicates the current value of a metric describing each pod
 * in the current scale target (for example,
 * transactions-processed-per-second).
 */
public class V2alpha1PodsMetricStatus {
    /**
     * currentAverageValue is the current value of the average of the metric
     * across all relevant pods (as a quantity).
     */
    @JsonProperty(value = "currentAverageValue", required = true)
    private String currentAverageValue;

    /**
     * metricName is the name of the metric in question.
     */
    @JsonProperty(value = "metricName", required = true)
    private String metricName;

    /**
     * Get the currentAverageValue value.
     *
     * @return the currentAverageValue value
     */
    public String currentAverageValue() {
        return this.currentAverageValue;
    }

    /**
     * Set the currentAverageValue value.
     *
     * @param currentAverageValue the currentAverageValue value to set
     * @return the V2alpha1PodsMetricStatus object itself.
     */
    public V2alpha1PodsMetricStatus withCurrentAverageValue(String currentAverageValue) {
        this.currentAverageValue = currentAverageValue;
        return this;
    }

    /**
     * Get the metricName value.
     *
     * @return the metricName value
     */
    public String metricName() {
        return this.metricName;
    }

    /**
     * Set the metricName value.
     *
     * @param metricName the metricName value to set
     * @return the V2alpha1PodsMetricStatus object itself.
     */
    public V2alpha1PodsMetricStatus withMetricName(String metricName) {
        this.metricName = metricName;
        return this;
    }

}
