/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * HorizontalPodAutoscalerSpec describes the desired functionality of the
 * HorizontalPodAutoscaler.
 */
public class V2alpha1HorizontalPodAutoscalerSpec {
    /**
     * maxReplicas is the upper limit for the number of replicas to which the
     * autoscaler can scale up. It cannot be less that minReplicas.
     */
    @JsonProperty(value = "maxReplicas", required = true)
    private int maxReplicas;

    /**
     * metrics contains the specifications for which to use to calculate the
     * desired replica count (the maximum replica count across all metrics will
     * be used).  The desired replica count is calculated multiplying the ratio
     * between the target value and the current value by the current number of
     * pods.  Ergo, metrics used must decrease as the pod count is increased,
     * and vice-versa.  See the individual metric source types for more
     * information about how each type of metric must respond.
     */
    @JsonProperty(value = "metrics")
    private List<V2alpha1MetricSpec> metrics;

    /**
     * minReplicas is the lower limit for the number of replicas to which the
     * autoscaler can scale down. It defaults to 1 pod.
     */
    @JsonProperty(value = "minReplicas")
    private Integer minReplicas;

    /**
     * scaleTargetRef points to the target resource to scale, and is used to
     * the pods for which metrics should be collected, as well as to actually
     * change the replica count.
     */
    @JsonProperty(value = "scaleTargetRef", required = true)
    private V2alpha1CrossVersionObjectReference scaleTargetRef;

    /**
     * Get the maxReplicas value.
     *
     * @return the maxReplicas value
     */
    public int maxReplicas() {
        return this.maxReplicas;
    }

    /**
     * Set the maxReplicas value.
     *
     * @param maxReplicas the maxReplicas value to set
     * @return the V2alpha1HorizontalPodAutoscalerSpec object itself.
     */
    public V2alpha1HorizontalPodAutoscalerSpec withMaxReplicas(int maxReplicas) {
        this.maxReplicas = maxReplicas;
        return this;
    }

    /**
     * Get the metrics value.
     *
     * @return the metrics value
     */
    public List<V2alpha1MetricSpec> metrics() {
        return this.metrics;
    }

    /**
     * Set the metrics value.
     *
     * @param metrics the metrics value to set
     * @return the V2alpha1HorizontalPodAutoscalerSpec object itself.
     */
    public V2alpha1HorizontalPodAutoscalerSpec withMetrics(List<V2alpha1MetricSpec> metrics) {
        this.metrics = metrics;
        return this;
    }

    /**
     * Get the minReplicas value.
     *
     * @return the minReplicas value
     */
    public Integer minReplicas() {
        return this.minReplicas;
    }

    /**
     * Set the minReplicas value.
     *
     * @param minReplicas the minReplicas value to set
     * @return the V2alpha1HorizontalPodAutoscalerSpec object itself.
     */
    public V2alpha1HorizontalPodAutoscalerSpec withMinReplicas(Integer minReplicas) {
        this.minReplicas = minReplicas;
        return this;
    }

    /**
     * Get the scaleTargetRef value.
     *
     * @return the scaleTargetRef value
     */
    public V2alpha1CrossVersionObjectReference scaleTargetRef() {
        return this.scaleTargetRef;
    }

    /**
     * Set the scaleTargetRef value.
     *
     * @param scaleTargetRef the scaleTargetRef value to set
     * @return the V2alpha1HorizontalPodAutoscalerSpec object itself.
     */
    public V2alpha1HorizontalPodAutoscalerSpec withScaleTargetRef(V2alpha1CrossVersionObjectReference scaleTargetRef) {
        this.scaleTargetRef = scaleTargetRef;
        return this;
    }

}
