/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package io.k8s.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Info contains versioning information. how we'll want to distribute that
 * information.
 */
public class VersionInfo {
    /**
     * The buildDate property.
     */
    @JsonProperty(value = "buildDate", required = true)
    private String buildDate;

    /**
     * The compiler property.
     */
    @JsonProperty(value = "compiler", required = true)
    private String compiler;

    /**
     * The gitCommit property.
     */
    @JsonProperty(value = "gitCommit", required = true)
    private String gitCommit;

    /**
     * The gitTreeState property.
     */
    @JsonProperty(value = "gitTreeState", required = true)
    private String gitTreeState;

    /**
     * The gitVersion property.
     */
    @JsonProperty(value = "gitVersion", required = true)
    private String gitVersion;

    /**
     * The goVersion property.
     */
    @JsonProperty(value = "goVersion", required = true)
    private String goVersion;

    /**
     * The major property.
     */
    @JsonProperty(value = "major", required = true)
    private String major;

    /**
     * The minor property.
     */
    @JsonProperty(value = "minor", required = true)
    private String minor;

    /**
     * The platform property.
     */
    @JsonProperty(value = "platform", required = true)
    private String platform;

    /**
     * Get the buildDate value.
     *
     * @return the buildDate value
     */
    public String buildDate() {
        return this.buildDate;
    }

    /**
     * Set the buildDate value.
     *
     * @param buildDate the buildDate value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withBuildDate(String buildDate) {
        this.buildDate = buildDate;
        return this;
    }

    /**
     * Get the compiler value.
     *
     * @return the compiler value
     */
    public String compiler() {
        return this.compiler;
    }

    /**
     * Set the compiler value.
     *
     * @param compiler the compiler value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withCompiler(String compiler) {
        this.compiler = compiler;
        return this;
    }

    /**
     * Get the gitCommit value.
     *
     * @return the gitCommit value
     */
    public String gitCommit() {
        return this.gitCommit;
    }

    /**
     * Set the gitCommit value.
     *
     * @param gitCommit the gitCommit value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withGitCommit(String gitCommit) {
        this.gitCommit = gitCommit;
        return this;
    }

    /**
     * Get the gitTreeState value.
     *
     * @return the gitTreeState value
     */
    public String gitTreeState() {
        return this.gitTreeState;
    }

    /**
     * Set the gitTreeState value.
     *
     * @param gitTreeState the gitTreeState value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withGitTreeState(String gitTreeState) {
        this.gitTreeState = gitTreeState;
        return this;
    }

    /**
     * Get the gitVersion value.
     *
     * @return the gitVersion value
     */
    public String gitVersion() {
        return this.gitVersion;
    }

    /**
     * Set the gitVersion value.
     *
     * @param gitVersion the gitVersion value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withGitVersion(String gitVersion) {
        this.gitVersion = gitVersion;
        return this;
    }

    /**
     * Get the goVersion value.
     *
     * @return the goVersion value
     */
    public String goVersion() {
        return this.goVersion;
    }

    /**
     * Set the goVersion value.
     *
     * @param goVersion the goVersion value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withGoVersion(String goVersion) {
        this.goVersion = goVersion;
        return this;
    }

    /**
     * Get the major value.
     *
     * @return the major value
     */
    public String major() {
        return this.major;
    }

    /**
     * Set the major value.
     *
     * @param major the major value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withMajor(String major) {
        this.major = major;
        return this;
    }

    /**
     * Get the minor value.
     *
     * @return the minor value
     */
    public String minor() {
        return this.minor;
    }

    /**
     * Set the minor value.
     *
     * @param minor the minor value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withMinor(String minor) {
        this.minor = minor;
        return this;
    }

    /**
     * Get the platform value.
     *
     * @return the platform value
     */
    public String platform() {
        return this.platform;
    }

    /**
     * Set the platform value.
     *
     * @param platform the platform value to set
     * @return the VersionInfo object itself.
     */
    public VersionInfo withPlatform(String platform) {
        this.platform = platform;
        return this;
    }

}
